---
apiVersion: v1
kind: Service
metadata:
  name: ${SCH_DEPLOYMENT_NAME}
  labels:
    app: ${SCH_DEPLOYMENT_NAME}
spec:
  type: NodePort
  ports:
  - name: http
    port: 18635
    targetPort: 18630
    protocol: TCP
  selector:
    app: ${SCH_DEPLOYMENT_NAME}
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: ${SCH_DEPLOYMENT_NAME}
  annotations:
    kubernetes.io/ingress.class: traefik
spec:
  rules:
  - host:
    http:
      paths:
      - path: /
        backend:
          serviceName: ${SCH_DEPLOYMENT_NAME}
          servicePort: 18635
