apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${SCH_DEPLOYMENT_NAME}
    namespace: ${KUBE_NAMESPACE}
  spec:
    replicas: 1
    selector:
      matchLabels:
        app: streamsets-datacollector
    template:
      metadata:
        labels:
          app : streamsets-datacollector
      spec:
        containers:
        - name : datacollector
          image: ${SDC_DOCKER_IMAGE}:${SDC_DOCKER_TAG}
          ports:
          - containerPort: 18630
          env:
          - name: HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
        imagePullSecrets:
        - name: dockerstore
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: datacollector-hpa
    namespace: ${KUBE_NAMESPACE}
  spec:
    scaleTargetRef:
      apiVersion: apps/v1beta1
      kind: Deployment
      name: streamsets-datacollector
    minReplicas: 1
    maxReplicas: 10
    targetCPUUtilizationPercentage: 50
