apiVersion: v1
kind: List
items:
- apiVersion: apps/v1
  kind: Deployment
  metadata:
    name: ${SCH_DEPLOYMENT_NAME}
  spec:
    replicas: ${SDC_REPLICAS}
    selector:
      matchLabels:
        app: ${SCH_DEPLOYMENT_NAME}
    template:
      metadata:
        labels:
          app : ${SCH_DEPLOYMENT_NAME}
      spec:
        containers:
        - name : datacollector
          image: ${SDC_DOCKER_IMAGE}:${SDC_DOCKER_TAG}
          ports:
          - containerPort: 18630
          env:
          - name: HOST
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          resources:
            requests:
              cpu: ${SDC_CPUS}
        imagePullSecrets:
        - name: dockerstore
- apiVersion: autoscaling/v1
  kind: HorizontalPodAutoscaler
  metadata:
    name: ${SCH_DEPLOYMENT_NAME}-hpa
  spec:
    scaleTargetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: ${SCH_DEPLOYMENT_NAME}
    minReplicas: ${SDC_REPLICAS_MIN}
    maxReplicas: ${SDC_REPLICAS_MAX}
    targetCPUUtilizationPercentage: ${SDC_REPLICAS_CPU_THRESHOLD}
