
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SCH_DEPLOYMENT_NAME}
  namespace: ${KUBE_NAMESPACE}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${SCH_DEPLOYMENT_NAME}
  template:
    metadata:
      labels:
        app : ${SCH_DEPLOYMENT_NAME}
    spec:
      containers:
      - name : datacollector
        image: ${SDC_DOCKER_IMAGE}:${SDC_DOCKER_TAG}
        ports:
        - containerPort: 18630
        env:
        - name: SDC_CONF_SDC_BASE_HTTP_URL
          value: https://${external_ip}:443
        - name: SDC_CONF_HTTP_ENABLE_FORWARDED_REQUESTS
          value: true
      imagePullSecrets:
      - name: dockerstore
