apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SCH_DEPLOYMENT_NAME}
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ${SCH_DEPLOYMENT_NAME}
  template:
    metadata:
      labels:
        app : ${SCH_DEPLOYMENT_NAME}
    spec:
      containers:
      - name : datacollector
        image: ${SDC_DOCKER_IMAGE}:${SDC_DOCKER_TAG}
        ports:
        - containerPort: 18630
        env:
        - name: SDC_CONF_SDC_BASE_HTTP_URL
          value: ${sdc_protocol}://${sdc_host}:${sdc_port}
          #value: https://${external_ip}:${INGRESS_PORT_HTTPS}/${SCH_DEPLOYMENT_NAME}
        - name: SDC_CONF_HTTP_ENABLE_FORWARDED_REQUESTS
          value: true
      imagePullSecrets:
      - name: dockerstore
