
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ${SCH_DEPLOYMENT_NAME}
spec:
  replicas: ${SDC_REPLICAS}
  selector:
    matchLabels:
      app: ${SCH_DEPLOYMENT_NAME}
  template:
    metadata:
      labels:
        app : ${SCH_DEPLOYMENT_NAME}
    spec:
      containers:
      - name : datacollector
        image: ${SDC_DOCKER_IMAGE}:${SDC_DOCKER_TAG}
        ports:
        - containerPort: 18630
        env:
        - name: HOST
          valueFrom:
            fieldRef:
              fieldPath: status.podIP
        resources:
          requests:
            cpu: ${SDC_CPUS}
      imagePullSecrets:
      - name: dockerstore
