---
kind: Deployment
apiVersion: extensions/v1beta1
metadata:
  name: ${INGRESS_NAME}-ingress-controller
  labels:
    k8s-app: ${INGRESS_NAME}-ingress-lb
spec:
  replicas: 1
  selector:
    matchLabels:
      k8s-app: ${INGRESS_NAME}-ingress-lb
  template:
    metadata:
      labels:
        k8s-app: ${INGRESS_NAME}-ingress-lb
        name: ${INGRESS_NAME}-ingress-lb
    spec:
      serviceAccountName: ${INGRESS_NAME}-ingress-controller
      terminationGracePeriodSeconds: 60
      volumes:
      - name: ssl
        secret:
          secretName: ${INGRESS_NAME}-cert
      - name: config
        configMap:
          name: ${INGRESS_NAME}-conf
      containers:
      - image: traefik:1.7-alpine
        name: ${INGRESS_NAME}-ingress-lb
        imagePullPolicy: Always
        volumeMounts:
        - mountPath: "/ssl"
          name: "ssl"
        - mountPath: "/config"
          name: "config"
        args:
        - --web
        - --kubernetes
        - --kubernetes.ingressclass=traefik-${SCH_DEPLOYMENT_NAME}        
        - --configfile=/config/traefik.toml
        - --logLevel=DEBUG
---
kind: Service
apiVersion: v1
metadata:
  name: ${INGRESS_NAME}-ingress-service
spec:
  type: LoadBalancer
  selector:
    k8s-app: ${INGRESS_NAME}-ingress-lb
  ports:
    - protocol: TCP
      port: ${INGRESS_PORT_HTTP}
      name: http
    - protocol: TCP
      port: ${INGRESS_PORT_HTTPS}
      name: https
    - protocol: TCP
      port: 8080
      name: admin
