
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: authoring-datacollector
  namespace: ${KUBE_NAMESPACE}
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app : authoring-datacollector
    spec:
      containers:
      - name : datacollector
        image: ${SDC_DOCKER_IMAGE}:${SDC_DOCKER_TAG}
        ports:
        - containerPort: 18630
        env:
        - name: SDC_CONF_SDC_BASE_HTTP_URL
          value: https://${external_ip}:443
        - name: SDC_CONF_HTTP_ENABLE_FORWARDED_REQUESTS
          value: true
      imagePullSecrets:
      - name: dockerstore
